[build]
  publish = "release/wwwroot"
  command = "wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh && chmod +x dotnet-install.sh && ./dotnet-install.sh --channel 10.0 && export PATH=\"$PATH:$HOME/.dotnet\" && dotnet publish -c Release -o release"