[build]
  command = "curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 10.0 && $HOME/.dotnet/dotnet publish -c Release -o release"
  publish = "release/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200